spring.application.name: employee-api
server.port: 8111
employee:
  service:
    baseUrl: http://localhost:8112/api/v1/employee

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: employee-app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB